export const PRODUCT_GET_INFO = 'PRODUCT_GET_INFO';
export const PRODUCT_GET_REVIEWS = 'PRODUCT_GET_REVIEW';
export const PRODUCT_GET_QA = 'PRODUCT_GET_QA';
export const PRODUCT_GET_SPONSOR = 'PRODUCT_GET_SPONSOR';

export const PRODUCT_SET_INFO = 'PRODUCT_SET_INFO';
export const PRODUCT_SET_REVIEWS = 'PRODUCT_SET_REVIEW';
export const PRODUCT_SET_QA = 'PRODUCT_SET_QA';
export const PRODUCT_SET_SPONSOR = 'PRODUCT_SET_SPONSOR';
export const PRODUCT_SET_ALSOLIKE = 'PRODUCT_SET_ALSOLIKE';
